# [Tarea 09] Ejercicios Unidad 04-A-B | Eliminación gaussiana vs Gauss-Jordan

-----------------
### EJERCICIO UNO
Para cada uno de los siguientes sistemas lineales, obtenga, de ser posible, una solución con métodos gráficos.
Explique los resultados desde un punto de vista geométrico.
### RESOLUCIÓN

In [3]:
%load_ext autoreload
import numpy as np
from src import eliminacion_gaussiana_redondeo,eliminacion_gaussiana, multiplicar_matriz_vector
from src import gauss_jordan

[01-10 21:04:55][INFO] 2025-01-10 21:04:55.140642
[01-10 21:04:55][INFO] 2025-01-10 21:04:55.141881
[01-10 21:04:55][INFO] 2025-01-10 21:04:55.143524


#### SISTEMA DE ECUACIONES A
$$ x_1 + 2x_2 = 0 $$  
$$ x_1 - x_2 = 0 $$

In [9]:
%autoreload 2
A = [[1,2,0],[1,-1,0]]
sol_a = eliminacion_gaussiana_redondeo(A)
print("La solución es:",sol_a)

[01-10 21:20:00][INFO] 
[[ 1.  2.  0.]
 [ 0. -3.  0.]]
La solución es: [ 0. -0.]


#### SISTEMA DE ECUACIONES B
$$ x_1 + 2x_2 = 3 $$  
$$ -2x_1 - 4x_2 = 6 $$

In [11]:
%autoreload 2
A = [[1,2,3],[-2,-4,6]]
sol_a = eliminacion_gaussiana_redondeo(A)
print("La solución es:",sol_a)

[01-10 21:20:42][INFO] 
[[-2. -4.  6.]
 [ 0.  0.  6.]]

No existe solución.
La solución es: None


#### SISTEMA DE ECUACIONES C
$$ 2x_1 + x_2 = -1 $$  
$$ x_1 + x_2 = 2 $$  
$$ x_1 - 3x_2 = 5 $$

In [12]:
%autoreload 2
A = [[2,1,-1],[1,1,2],[1,-3,5]]
sol_a = eliminacion_gaussiana_redondeo(A)
print("La solución es:",sol_a)

AssertionError: La matriz A debe ser de tamaño n-by-(n+1).

#### SISTEMA DE ECUACIONES D
$$ 2x_1 + x_2 + x_3 = 1 $$  
$$ 2x_1 + 4x_2 - x_3 = -1 $$

In [13]:
%autoreload 2
A = [[2,1,1,1],[2,4,-1,-1]]
sol_a = eliminacion_gaussiana_redondeo(A)
print("La solución es:",sol_a)

AssertionError: La matriz A debe ser de tamaño n-by-(n+1).

_________________
### EJERCICIO DOS
Utilice la eliminación gaussiana con sustitución hacia atrás y aritmética de redondeo de dos dígitos para resolver los siguientes sistemas lineales. No reordene las ecuaciones. (La solución exacta para cada sistema es $x_1 = -1$, $x_2 = 2$, $x_3 = 3$.
#### SISTEMA DE ECUACIONES A
$$-x_1 + 4x_2 + x_3 = 8$$

$$\dfrac{5}{3}x_1 + \dfrac{2}{3}x_2 + \dfrac{2}{3}x_3 = 1$$

$$2x_1 + x_2 + 4x_3 = 11$$


In [6]:
%autoreload 2
A = [[-1.0,4.0,1.0,8.0],[5/3,2/3,2/3,1.0],[2.0,1.0,4.0,11.0]]
sol_a = eliminacion_gaussiana_redondeo(A)
print("La solución es:",sol_a)

[01-10 21:18:21][INFO] 
[[ 2.00e+00  1.00e+00  4.00e+00  1.10e+01]
 [ 1.00e-02 -1.60e-01 -2.65e+00 -8.13e+00]
 [ 0.00e+00  4.50e+00  3.00e+00  1.35e+01]]
[01-10 21:18:21][INFO] 
[[ 2.00e+00  1.00e+00  4.00e+00  1.10e+01]
 [ 0.00e+00  4.50e+00  3.00e+00  1.35e+01]
 [ 1.00e-02  2.00e-02 -2.53e+00 -7.59e+00]]
La solución es: [-1.  1.  3.]


#### SISTEMA DE ECUACIONES B

 $$4x_1+2x_2-x_3 = -5$$

 $$\dfrac{1}{9}x_1+\dfrac{1}{9}x_2-\dfrac{1}{3}x_3 = -1$$
 
 $$x_1+4x_2+2x_3=9$$

In [5]:
B = [[4,2,-1,-5],[1/9,1/9,-1/3,-1],[1,4,2,9]]
sol_b = eliminacion_gaussiana_redondeo(B)
print("La solución es:",sol_b)

[01-10 21:04:55][INFO] 
[[ 4.000e+00  2.000e+00 -1.000e+00 -5.000e+00]
 [-1.000e-02  5.000e-02 -3.000e-01 -8.500e-01]
 [ 0.000e+00  3.500e+00  2.250e+00  1.025e+01]]
[01-10 21:04:55][INFO] 
[[ 4.000e+00  2.000e+00 -1.000e+00 -5.000e+00]
 [ 0.000e+00  3.500e+00  2.250e+00  1.025e+01]
 [-1.000e-02  1.000e-02 -3.200e-01 -9.500e-01]]
La solución es: [-1.02     1.02     2.96875]


-------------------------
### EJERCICIO TRES
Utilice el algoritmo de eliminación gaussiana para resolver, de ser posible, los siguientes sistemas lineales, y
determine si se necesitan intercambios de fila:

#### SISTEMA DE ECUACIONES A
$$ x_1 - x_2 + 3x_3 = 2 $$  
$$ 3x_1 - 3x_2 + x_3 = -1, $$
$$ x_1 + x_2 = 3, $$  


In [14]:
A = [[1,-1,3,2],[3,-3,1,-1],[1,1,0,3]]
sol_a = eliminacion_gaussiana(A)
print("\nLa solución es:",sol_a)

[01-10 21:24:52][INFO] 
[[ 3.         -3.          1.         -1.        ]
 [ 0.          0.          2.6666667   2.3333333 ]
 [ 0.          2.         -0.33333334  3.3333333 ]]
[01-10 21:24:52][INFO] 
[[ 3.         -3.          1.         -1.        ]
 [ 0.          2.         -0.33333334  3.3333333 ]
 [ 0.          0.          2.6666667   2.3333333 ]]

La solución es: [1.1875     1.8125     0.87499994]


#### SISTEMA DE ECUACIONES B
$$ 2x_1 - 1.5x_2 + 3x_3 = 1, $$  
$$ -x_1 + 2x_3 = 3, $$  
$$ 4x_1 - 4.5x_2 + 5x_3 = 1, $$

In [15]:
B = [[2,-1.5,3,1],[-1,0,2,3],[4,-4.5,5,1]]
sol_b = eliminacion_gaussiana(B)
print("\nLa solución es:",sol_b)

[01-10 21:25:17][INFO] 
[[ 4.    -4.5    5.     1.   ]
 [ 0.    -1.125  3.25   3.25 ]
 [ 0.     0.75   0.5    0.5  ]]
[01-10 21:25:17][INFO] 
[[ 4.        -4.5        5.         1.       ]
 [ 0.        -1.125      3.25       3.25     ]
 [ 0.         0.         2.6666667  2.6666667]]

La solución es: [-1. -0.  1.]


#### SISTEMA DE ECUACIONES C
$$ 2x_1 = 3$$
$$ x_1 + 1.5x_2 = 4.5, $$  
$$ -3x_2 + 0.5x_3 = -6.6, $$  
$$ 2x_1 - 2x_2 + x_3 + x_4 = 0.8, $$ 

In [16]:
C = [[2,0,0,0,3],[1,1.5,0,0,4.5],[0,-3,0.5,0,-6.6],[2,-2,1,1,0.8]]
sol_c = eliminacion_gaussiana(C)
print("\nLa solución es:",sol_c)

[01-10 21:25:24][INFO] 
[[ 2.   0.   0.   0.   3. ]
 [ 0.   1.5  0.   0.   3. ]
 [ 0.  -3.   0.5  0.  -6.6]
 [ 0.  -2.   1.   1.  -2.2]]
[01-10 21:25:24][INFO] 
[[ 2.          0.          0.          0.          3.        ]
 [ 0.         -3.          0.5         0.         -6.6       ]
 [ 0.          0.          0.25        0.         -0.29999995]
 [ 0.          0.          0.6666666   1.          2.2       ]]
[01-10 21:25:24][INFO] 
[[ 2.          0.          0.          0.          3.        ]
 [ 0.         -3.          0.5         0.         -6.6       ]
 [ 0.          0.          0.6666666   1.          2.2       ]
 [ 0.          0.          0.         -0.37500003 -1.125     ]]

La solución es: [ 1.5        2.        -1.1999997  2.9999998]


#### SISTEMA DE ECUACIONES D
$$ x_1 + x_2 + x_4 = 2, $$  
$$ 2x_1 + x_2 - x_3 + x_4 = 1, $$  
$$ 4x_1 - x_2 - 2x_3 + 2x_4 = 0, $$  
$$ 3x_1 - x_2 - x_3 + 2x_4 = -3. $$

In [17]:
D = [[1,1,0,1,2],[2,1,-1,1,1],[4,-1,-2,2,0],[3,-1,-1,2,-3]]
sol_d = eliminacion_gaussiana(D)

[01-10 21:25:32][INFO] 
[[ 4.   -1.   -2.    2.    0.  ]
 [ 0.    1.5   0.    0.    1.  ]
 [ 0.    1.25  0.5   0.5   2.  ]
 [ 0.   -0.25  0.5   0.5  -3.  ]]
[01-10 21:25:32][INFO] 
[[ 4.        -1.        -2.         2.         0.       ]
 [ 0.         1.5        0.         0.         1.       ]
 [ 0.         0.         0.5        0.5        1.1666667]
 [ 0.         0.         0.5        0.5       -2.8333333]]
[01-10 21:25:32][INFO] 
[[ 4.        -1.        -2.         2.         0.       ]
 [ 0.         1.5        0.         0.         1.       ]
 [ 0.         0.         0.5        0.5        1.1666667]
 [ 0.         0.         0.         0.        -4.       ]]

No existe solución.


-------------------------
### EJERCICIO CUATRO
Use el algoritmo de eliminación gaussiana y la aritmética computacional de precisión de 32 bits para resolver los
siguientes sistemas lineales.

#### SISTEMA DE ECUACIONES A
$$ \dfrac{1}{4}x_1 + \dfrac{1}{5}x_2 + \dfrac{1}{6}x_3 = 9,$$
$$ \dfrac{1}{3}x_1 + \dfrac{1}{4}x_2 + \dfrac{1}{5}x_3 = 8, $$  
$$ \dfrac{1}{2}x_1 + x_2 + 2x_3 = 8. $$  

In [18]:
A = [[1/4,1/5,1/6,9],[1/3,1/4,1/5,8],[1/2,1,2,8]]
sol_a = eliminacion_gaussiana(A)
print("\nLa solución es:",sol_a)

[01-10 21:26:34][INFO] 
[[ 0.5        1.         2.         8.       ]
 [ 0.        -0.4166667 -1.1333333  2.6666665]
 [ 0.        -0.3       -0.8333333  5.       ]]
[01-10 21:26:34][INFO] 
[[ 0.5         1.          2.          8.        ]
 [ 0.         -0.4166667  -1.1333333   2.6666665 ]
 [ 0.          0.         -0.01733333  3.0800002 ]]

La solución es: [-227.07697  476.92322 -177.69237]


#### SISTEMA DE ECUACIONES B
$$ 3.333x_1 + 15920x_2 - 10.333x_3 = 15913, $$  
$$ 2.222x_1 + 16.71x_2 + 9.612x_3 = 28.544, $$  
$$ 1.5611x_1 + 5.1791x_2 + 1.6852x_3 = 8.4254. $$  

In [19]:
B = [[3.333,15920,-10.333,15913],[2.222,16.71,9.612,28.544],[1.5611,5.1791,1.6852,8.4254]]
sol_b = eliminacion_gaussiana(B)
print("\nLa solución es:",sol_b)


[01-10 21:26:42][INFO] 
[[ 3.3329999e+00  1.5920000e+04 -1.0333000e+01  1.5913000e+04]
 [ 0.0000000e+00 -1.0596623e+04  1.6500668e+01 -1.0580122e+04]
 [ 0.0000000e+00 -7.4513804e+03  6.5249376e+00 -7.4448555e+03]]
[01-10 21:26:42][INFO] 
[[ 3.3329999e+00  1.5920000e+04 -1.0333000e+01  1.5913000e+04]
 [ 0.0000000e+00 -1.0596623e+04  1.6500668e+01 -1.0580122e+04]
 [ 0.0000000e+00  0.0000000e+00 -5.0780745e+00 -5.0786133e+00]]

La solución es: [0.99970937 1.0000001  1.0001061 ]


#### SISTEMA DE ECUACIONES C
$$ x_1 + \dfrac{1}{2}x_2 + \dfrac{1}{3}x_3 + \dfrac{1}{4}x_4 = \dfrac{1}{6},$$
$$ \dfrac{1}{2}x_1 + \dfrac{1}{3}x_2 + \dfrac{1}{4}x_3 + \dfrac{1}{5}x_4 = \dfrac{1}{7}, $$
$$ \dfrac{1}{3}x_1 + \dfrac{1}{4}x_2 + \dfrac{1}{5}x_3 + \dfrac{1}{6}x_4 = \dfrac{1}{8}, $$  
$$ \dfrac{1}{4}x_1 + \dfrac{1}{5}x_2 + \dfrac{1}{6}x_3 + \dfrac{1}{7}x_4 = \dfrac{1}{9}. $$  


In [20]:
C = [[1,1/2,1/3,1/4,1/6],[1/2,1/3,1/4,1/5,1/7],[1/3,1/4,1/5,1/6,1/8],[1/4,1/5,1/6,1/7,1/9]]
sol_c = eliminacion_gaussiana(C)
print("\nLa solución es:",sol_c)

[01-10 21:26:50][INFO] 
[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.         0.08333334 0.08333333 0.075      0.05952381]
 [0.         0.08333333 0.08888888 0.08333334 0.06944444]
 [0.         0.075      0.08333334 0.08035715 0.06944445]]
[01-10 21:26:50][INFO] 
[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.         0.08333334 0.08333333 0.075      0.05952381]
 [0.         0.         0.00555557 0.00833335 0.00992064]
 [0.         0.         0.00833335 0.01285715 0.01587302]]
[01-10 21:26:50][INFO] 
[[ 1.0000000e+00  5.0000000e-01  3.3333334e-01  2.5000000e-01
   1.6666667e-01]
 [ 0.0000000e+00  8.3333343e-02  8.3333328e-02  7.5000003e-02
   5.9523813e-02]
 [ 0.0000000e+00  0.0000000e+00  8.3333477e-03  1.2857154e-02
   1.5873022e-02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00 -2.3809634e-04
  -6.6138618e-04]]

La solución es: [-0.03174745  0.59525675 -2.3809996   2.7778091 ]


#### SISTEMA DE ECUACIONES D
$$ 2x_1 + x_2 - x_3 + x_4 - 3x_5 = 7,$$ 
$$ x_1 + 2x_3 - x_4 + x_5 = 2, $$  
$$ -2x_2 - x_3 + x_4 - x_5 = -5, $$  
$$ 3x_1 + x_2 - 4x_3 + 5x_5 = 6, $$  
$$ x_1 - x_2 - x_3 - x_4 + x_5 = -3.$$  

In [21]:
D = [[2,1,-1,1,-3,7],[1,0,2,-1,1,2],[0,-2,-1,1,-1,-5],[3,1,-4,0,5,6],[1,-1,-1,-1,1,-3]]
sol_d = eliminacion_gaussiana(D)
print("\nLa solución es:",sol_d)

[01-10 21:26:57][INFO] 
[[ 3.          1.         -4.          0.          5.          6.        ]
 [ 0.         -0.33333334  3.3333335  -1.         -0.66666675  0.        ]
 [ 0.         -2.         -1.          1.         -1.         -5.        ]
 [ 0.          0.3333333   1.6666667   1.         -6.3333335   3.        ]
 [ 0.         -1.3333334   0.33333337 -1.         -0.66666675 -5.        ]]
[01-10 21:26:57][INFO] 
[[ 3.0000000e+00  1.0000000e+00 -4.0000000e+00  0.0000000e+00
   5.0000000e+00  6.0000000e+00]
 [ 0.0000000e+00 -2.0000000e+00 -1.0000000e+00  1.0000000e+00
  -1.0000000e+00 -5.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  3.5000002e+00 -1.1666666e+00
  -5.0000006e-01  8.3333337e-01]
 [ 0.0000000e+00  0.0000000e+00  1.5000001e+00  1.1666666e+00
  -6.5000000e+00  2.1666667e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00 -1.6666667e+00
  -5.9604645e-08 -1.6666665e+00]]
[01-10 21:26:57][INFO] 
[[ 3.          1.         -4.          0.          5.          6.        ]
 

-------------------------
### EJERCICIO CINCO

Dado el sistema lineal:

$$x_1 - x_2 + \alpha x_3 = -2$$

$$-x_1 + 2x_2 - \alpha x_3 = 3$$

$$\alpha x_1 + x_2 + x_3 = 2$$

a. Encuentre el valor(es) de $\alpha$ para los que el sistema no tiene soluciones.

b. Encuentre el valor(es) de $\alpha$ para los que el sistema tiene un número infinito de soluciones.

c. Suponga que existe una única solución para un valor determinado de $\alpha$, encuentre la solución.



In [27]:
def analyze_system(alpha):
    matrix = [
        [1, -1, alpha],
        [-1, 2, -alpha],
        [alpha, 1, 1]
    ]
    vector = [-2, 3, 2]

    try:
        # Convertir a matrices numpy
        matrix = np.array(matrix, dtype=float)
        vector = np.array(vector, dtype=float)

        # Intentar resolver el sistema
        solution = np.linalg.solve(matrix, vector)
        return solution
    except np.linalg.LinAlgError:
        return "No tiene solución o tiene infinitas soluciones"

alphas = [-1, 0, 1]
for alpha in alphas:
    result = analyze_system(alpha)
    print(f"Para α = {alpha}, la solución es: {result}")

Para α = -1, la solución es: No tiene solución o tiene infinitas soluciones
Para α = 0, la solución es: [-1.  1.  1.]
Para α = 1, la solución es: No tiene solución o tiene infinitas soluciones



---
### EJERCICIO SEIS
Suponga que en un sistema biológico existen $n$ especies de animales y $m$ fuentes de alimento. Si $x_j$ representa la población de la $j$-ésima especie, para cada $j = 1, \ldots, n$; $b_i$ representa el suministro diario disponible del $i$-ésimo alimento y $a_{ij}$ representa la cantidad del $i$-ésimo alimento consumida por la $j$-ésima especie.

$$a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1,$$  
$$a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2,$$  
$$\vdots \hspace{1.5cm} \vdots \hspace{2.2cm} \vdots \hspace{1cm} \vdots  $$
$$a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n = b_m,$$  

Esto representa un equilibrio donde existe un suministro diario de alimento para cumplir con precisión con el promedio diario de consumo de cada especie.

a. Si  

\begin{equation*}
    A = [a_{ij}] =
    \begin{bmatrix}
        1 & 2 & 0 & 3 \\
        1 & 0 & 2 & 2 \\
        0 & 0 & 1 & 1
    \end{bmatrix}
\end{equation*}

$ \textbf{x} = (x_j)=[1000, 500, 350, 400],$ y $\textbf{b}= (b_i) = [3500, 2700, 900]$. ¿Existe suficiente alimento para satisfacer el consumo promedio diario? 

¿Existe suficiente alimento para satisfacer el consumo promedio diario?

In [23]:
A = np.array([[1,2,0,3],[1,0,2,2],[0,0,1,1]])
x = np.array([1000,500,350,400])

b_obtenido =  multiplicar_matriz_vector(A,x)
print("El vector de consumo promedio diario es de:",b_obtenido)

El vector de consumo promedio diario es de: [3200. 2500.  750.]


**b.** ¿Cuál es el número máximo de animales de cada especie que se podría agregar de forma individual al sistema con el suministro de alimento que cumpla con el consumo?

In [24]:
A = np.array([[1,2,0,3],[1,0,2,2],[0,0,1,1]])
x = np.array([1005,511,355,491])

b_obtenido =  multiplicar_matriz_vector(A,x)
print("El vector de consumo promedio diario es de:",b_obtenido)

El vector de consumo promedio diario es de: [3500. 2697.  846.]


**c.** Si la especie 1 se extingue, ¿qué cantidad de incremento individual de las especies restantes se podría soportar?

In [25]:
A = np.array([[1,2,0,3],[1,0,2,2],[0,0,1,1]])
x = np.array([0,1000,400,500])

b_obtenido =  multiplicar_matriz_vector(A,x)
print("El vector de consumo promedio diario es de:",b_obtenido)

El vector de consumo promedio diario es de: [3500. 1800.  900.]


**d.** Si la especie 2 se extingue, ¿qué cantidad de incremento individual de las especies restantes se podría soportar?

In [26]:
A = np.array([[1,2,0,3],[1,0,2,2],[0,0,1,1]])
x = np.array([1080,0,380,430])

b_obtenido =  multiplicar_matriz_vector(A,x)
print("El vector de consumo promedio diario es de:",b_obtenido)

El vector de consumo promedio diario es de: [2370. 2700.  810.]


En el caso de que la especie 2 se extinga, las poblaciones de las demás especies se verían beneficiadas con los siguientes aumentos:

- Especie 1: Un incremento significativo de 80, lo cual indica una mayor capacidad de aprovechar los recursos disponibles.
- Especie 3: Un aumento de 30, demostrando una adaptación moderada frente a la ausencia de la especie 2.
- Especie 4: También un incremento de 30, evidenciando un equilibrio en el uso de los recursos compartidos.